In [2]:
import numpy as np

In [3]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
n1.shape

(4,)

In [7]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zero

In [10]:
np.arange(-10, 10, .2)
x = np.arange(-10, 10, .2)
x.shape

(100,)

In [14]:
y = np.linspace(1, 5, 25)
print(y)
print(y.shape)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]
(25,)


In [25]:
np.random.rand(3,3)

array([[0.06899208, 0.25914343, 0.30474614],
       [0.96864176, 0.27994539, 0.36663488],
       [0.1180971 , 0.12656348, 0.37639098]])

In [17]:
np.random.rand(10)

array([0.84496275, 0.42141498, 0.67912642, 0.26167705, 0.20528528,
       0.22069329, 0.15729115, 0.17687831, 0.14648365, 0.7566961 ])

In [26]:
np.random.randint(1, 1000, (5,5))

array([[118, 475,   2, 736, 973],
       [ 10, 510,  42, 185,  25],
       [858, 483, 476, 277, 324],
       [526, 305, 163, 942, 332],
       [ 16, 982, 671, 881, 835]])

In [27]:
x = np.random.randint(1,11,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[2 4]
 [4 3]
 [6 6]]
[[1 1]
 [1 5]
 [2 8]]


In [28]:
x+5

array([[ 7,  9],
       [ 9,  8],
       [11, 11]])

In [29]:
x+y

array([[ 3,  5],
       [ 5,  8],
       [ 8, 14]])

In [30]:
x*y

array([[ 2,  4],
       [ 4, 15],
       [12, 48]])

In [31]:
x.T

array([[2, 4, 6],
       [4, 3, 6]])

In [32]:
x.dot(y.T)

array([[ 6, 22, 36],
       [ 7, 19, 32],
       [12, 36, 60]])

In [33]:
np.sin(x)

array([[ 0.90929743, -0.7568025 ],
       [-0.7568025 ,  0.14112001],
       [-0.2794155 , -0.2794155 ]])

In [36]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())


25
4.166666666666667
1.4624940645653537
2
6
